# Tipos int e float
# int -> Numero inteiro
# O tipo int representa qualquer numero
# posito ou negativo. int sem sinal é considerado
# positivo.
# print(11) # int
# print(-11) # int
# print(0)

# float -> Numero com ponto flutuante
# O tipo float representa qualquer numero
# posito ou negativo com ponto flutuante.
# float sem sinal é considerado positivo.
# print (1.1, 10.11)
# print (0.0, -1.5)

# A função type mostra o tipo que o Python
# inferiu ao valor
print( type('alexandre'))
print( type(0) )
print(type(1.1), type(-1.1), type(0.0))